### PR TITLE
Python version of quote_to_image script

### PR DESCRIPTION
**Pull request by avalonv**
Being incredibly fucking stubborn and pissed that I couldn't get the PHP version to run, I rewrote the whole thing in python (fun fact: I don't know shit about PHP).

The PHP script does work on Linux if you try super hard, but the python version is still considerably faster. Timing both of them on Linux, the php version took 7m46s (466s), the python one 62 seconds. On windows it takes just under two minutes.

It's also a LOOOT easier to install its dependencies on Windows. You don't have to fuss with php.ini files, xaamp, or whatever php developers debase themselves with, just one pip command to install pillow.

It'd be awesome if you could test it and let me know what you think. Don't have my kindle on hand atm so I couldn't test the whole project for myself

### CODE REVIEW

**Comment by avalonv** [comment]
Oh yeah another thing. The logic in the python script is more thorough, and it solves a bug with the php version. Basically, if the timestring is connected to another word via dashes or punctuation, it will get highlighted too, even if it's something irrelevant. This exemplifies the difference:

python:
image
php:
image

**Comment by elegantalchemist** [comment]
What an amazing update. I am only a hobby coder at best but i've quickly learned to hate PHP - this is mostly code from the original project and getting the dependencies together to let Windows run it was a PITA.

I have noted other errors through the PHP conversion as well. Text which is italicised gets treated badly - presumably as the PHP instructions specify exact fonts for each section and there's no way to italicise these. 

Thanks!

**Comment by elegantalchemist** [comment]
I can't get this python script to run in Windows - Pillow and Python are installed but I get an error straight away

Traceback (most recent call last):
  File "D:\Documents\General Stuff\Making Projects\Literary Clock\python\quote_to_image.py", line 245, in <module>
    main()
  File "D:\Documents\General Stuff\Making Projects\Literary Clock\python\quote_to_image.py", line 236, in main
    TurnQuoteIntoImage(i, row['time'],row['quote'],
KeyError: 'time'

Any ideas how to fix?

**Comment by avalonv** [comment]
Away from computer ATM but you're most likely using a quotes file without the CSV headers, which are needed with the Python version

**Comment by elegantalchemist** [comment]
> Away from computer ATM but you're most likely using a quotes file without the CSV headers, which are needed with the Python version

Spot on thanks, that was exactly it. I didn't realise you had a new version of the CSV file. Works perfectly, you're right about it parsing the times better.

On a related note, it looks like you've also gone through the CSV file to rid it of the italicised written in a TeX typeface which the PHP script can't deal with (it goes all wingdings). Awesome!

**Pull request merged**
